In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
data = pd.read_csv('/content/iris.csv')

In [4]:
data

ID  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0      1           5.1          3.5           1.4          0.2     setosa
1      2           4.9          3.0           1.4          0.2     setosa
2      3           4.7          3.2           1.3          0.2     setosa
3      4           4.6          3.1           1.5          0.2     setosa
4      5           5.0          3.6           1.4          0.2     setosa
..   ...           ...          ...           ...          ...        ...
145  146           6.7          3.0           5.2          2.3  virginica
146  147           6.3          2.5           5.0          1.9  virginica
147  148           6.5          3.0           5.2          2.0  virginica
148  149           6.2          3.4           5.4          2.3  virginica
149  150           5.9          3.0           5.1          1.8  virginica

[150 rows x 6 columns]

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   ID            150 non-null    int64  
 1   Sepal.Length  150 non-null    float64
 2   Sepal.Width   150 non-null    float64
 3   Petal.Length  150 non-null    float64
 4   Petal.Width   150 non-null    float64
 5   Species       150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [7]:
# Performing Label Encoding for categorical data.

from sklearn.preprocessing import LabelEncoder

labelEncoder = LabelEncoder()
data["speices_code"] = labelEncoder.fit_transform(data["Species"])
data[["speices_code", "Species"]]


speices_code    Species
0               0     setosa
1               0     setosa
2               0     setosa
3               0     setosa
4               0     setosa
..            ...        ...
145             2  virginica
146             2  virginica
147             2  virginica
148             2  virginica
149             2  virginica

[150 rows x 2 columns]

In [8]:
data

ID  Sepal.Length  Sepal.Width  ...  Petal.Width    Species speices_code
0      1           5.1          3.5  ...          0.2     setosa            0
1      2           4.9          3.0  ...          0.2     setosa            0
2      3           4.7          3.2  ...          0.2     setosa            0
3      4           4.6          3.1  ...          0.2     setosa            0
4      5           5.0          3.6  ...          0.2     setosa            0
..   ...           ...          ...  ...          ...        ...          ...
145  146           6.7          3.0  ...          2.3  virginica            2
146  147           6.3          2.5  ...          1.9  virginica            2
147  148           6.5          3.0  ...          2.0  virginica            2
148  149           6.2          3.4  ...          2.3  virginica            2
149  150           5.9          3.0  ...          1.8  virginica            2

[150 rows x 7 columns]

In [12]:
# Splitting the dataset

from sklearn.model_selection import train_test_split

x = data[['Sepal.Length', 'Sepal.Width', 'Petal.Length','Petal.Width']]
y = data[['speices_code']]

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [17]:
x_train.shape

(120, 4)

In [18]:
y_train.shape

(120, 1)

In [19]:
x_test.shape

(30, 4)

In [20]:
y_test.shape

(30, 1)

In [27]:
# Training the Model
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=3)

model.fit(x_train,y_train)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [28]:
predictions = model.predict(x_test)

In [25]:
# Plotting a confusion matrix

from sklearn.metrics import classification_report,confusion_matrix

print(confusion_matrix(predictions,y_test))

[[ 9  0  0]
 [ 0 11  0]
 [ 0  1  9]]


In [26]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      0.92      0.96        12
           2       0.90      1.00      0.95         9

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



In [ ]:
# Hence we have successfully created the K Nearest Neighbour Model


### **Thank You**